const KEY='baby-track-v2',OLD='baby-track-v1';
const defaults={version:2,profile:{name:'',birthDate:'',dueDate:''},entries:[],growth:[],milestones:{}};
const fresh=()=>JSON.parse(JSON.stringify(defaults));
let data=load();let insightDays=7;
function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem(OLD);if(!raw)return fresh();const parsed=JSON.parse(raw);return{...fresh(),...parsed,profile:{...defaults.profile,...(parsed.profile||{})},entries:Array.isArray(parsed.entries)?parsed.entries:[],growth:Array.isArray(parsed.growth)?parsed.growth:[],milestones:parsed.milestones&&typeof parsed.milestones==='object'?parsed.milestones:{}}}catch{return fresh()}}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={feed:'🍼',sleep:'🌙',diaper:'☁️',pump:'💧',tummy:'🧸',medicine:'⚕',note:'✎'},names={feed:'Feeding',sleep:'Sleep',diaper:'Diaper',pump:'Pumping',tummy:'Tummy time',medicine:'Medicine',note:'Note'};
const milestoneGroups=[['2 months',['Calms down when spoken to or picked up','Looks at your face','Smiles when you talk to or smile at them','Reacts to loud sounds','Watches you as you move','Holds head up when on tummy']],['4 months',['Smiles on own to get attention','Chuckles when you try to make them laugh','Makes sounds back when you talk','Turns head toward your voice','Holds head steady without support','Brings hands to mouth']],['6 months',['Knows familiar people','Laughs','Takes turns making sounds','Reaches to grab a toy','Rolls from tummy to back','Leans on hands to support sitting']],['9 months',['Looks when name is called','Shows several facial expressions','Makes repeated sounds like mamamama','Looks for objects dropped out of sight','Gets to sitting position','Sits without support']],['1 year',['Plays games like pat-a-cake','Waves bye-bye','Calls a parent mama or dada or another special name','Looks for things they see you hide','Pulls up to stand','Walks holding furniture']],['15 months',['Copies other children while playing','Shows affection','Tries to say one or two words besides mama or dada','Points to ask for something','Takes a few steps independently','Uses fingers to feed self']],['18 months',['Moves away but checks that you are close by','Points to show something interesting','Tries to say three or more words besides mama or dada','Follows one-step directions without gestures','Walks without holding on','Scribbles']],['2 years',['Notices when others are hurt or upset','Says at least two words together','Points to things in a book when asked','Runs','Kicks a ball','Eats with a spoon']],['30 months',['Plays next to and sometimes with other children','Says about 50 words','Says two or more words with one action word','Shows simple problem-solving skills','Jumps off the ground with both feet','Turns book pages one at a time']],['3 years',['Calms down within 10 minutes after caregiver leaves','Talks with at least two back-and-forth exchanges','Asks who, what, where, or why questions','Draws a circle when shown how','Puts on some clothes independently','Uses a fork']]];
const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));render()},id=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
const fmtTime=v=>new Date(v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),fmtDate=v=>new Date(v+'T12:00:00').toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'});
function age(){const d=data.profile.birthDate;if(!d)return data.profile.dueDate?`Due ${fmtDate(data.profile.dueDate)}`:'';const b=new Date(d+'T12:00:00'),n=new Date();let m=(n.getFullYear()-b.getFullYear())*12+n.getMonth()-b.getMonth()-(n.getDate()<b.getDate()?1:0);if(m<0)return'Our baby is arriving soon';if(m<1){const x=Math.max(0,Math.floor((n-b)/86400000));return`${x} day${x===1?'':'s'} old`}if(m<24)return`${m} month${m===1?'':'s'} old`;return`${Math.floor(m/12)} yr ${m%12} mo old`}
function render(){const now=new Date();$('#todayDate').textContent=now.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'});$('#greeting').textContent=data.profile.name?`${data.profile.name} ♡`:'Our Day';$('#babyAge').textContent=age()||"Set up our baby's profile to begin";const todays=data.entries.filter(e=>new Date(e.time).toDateString()===now.toDateString()),sum=t=>todays.filter(e=>e.type===t).length,sleep=todays.filter(e=>e.type==='sleep').reduce((a,e)=>a+(+e.duration||0),0);$('#todayStats').innerHTML=stat(sum('feed'),'feeds')+stat(sum('diaper'),'diapers')+stat(sleep?prettyMin(sleep):sum('sleep'),sleep?'sleep':'sleep logs')+stat(sum('pump'),'pumps');renderEntries($('#recentList'),sorted(data.entries).slice(0,6));renderTimers();renderTimeline();renderGrowth();renderMilestones();renderInsights()}
const stat=(v,l)=>`<div class="stat"><strong>${v}</strong><small>${l}</small></div>`,sorted=a=>a.slice().sort((x,y)=>new Date(y.time||y.date)-new Date(x.time||x.date)),prettyMin=m=>m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`;
function entryDetail(e){if(e.type==='sleep'&&e.duration)return prettyMin(+e.duration);if(['tummy','pump'].includes(e.type)&&e.duration)return`${e.duration} min`;if(e.type==='feed'){let x=e.detail||'';if(e.amount)x+=`${x?' · ':''}${e.amount} ${e.unit||'oz'}`;return x}return e.detail||''}
function renderEntries(el,arr){el.innerHTML=arr.length?arr.map(e=>`<div class="entry"><div class="entry-icon">${icons[e.type]||'•'}</div><div class="entry-body"><strong>${names[e.type]||e.type}${entryDetail(e)?` · ${esc(entryDetail(e))}`:''}</strong><small>${esc(e.note||'Logged')}</small></div><span class="entry-time">${fmtTime(e.time)}</span></div>`).join(''):'<div class="empty">Nothing logged yet.</div>'}
function renderTimeline(){const f=$('#filters .active')?.dataset.filter||'all';renderEntries($('#timelineList'),sorted(data.entries).filter(e=>f==='all'||e.type===f))}
function renderTimers(){const active=data.entries.filter(e=>e.active);$('#activeTimers').innerHTML=active.map(e=>`<div class="timer"><div><strong>${names[e.type]} in progress</strong><div class="muted">Started ${fmtTime(e.time)}</div></div><button data-stop="${e.id}">Stop</button></div>`).join('');$$('[data-stop]').forEach(b=>b.onclick=()=>{const e=data.entries.find(x=>x.id===b.dataset.stop);if(e){e.active=false;e.endTime=new Date().toISOString();e.duration=Math.max(1,Math.round((new Date(e.endTime)-new Date(e.time))/60000));save();toast(`${names[e.type]} saved`)}})}
function renderGrowth(){const g=sorted(data.growth),x=g[0];$('#growthLatest').innerHTML=x?metric(x.weight||'—','lb weight')+metric(x.length||'—','in length')+metric(x.head||'—','in head'):'<div class="empty">No measurements yet.</div>';$('#growthList').innerHTML=g.length?g.map(x=>`<div class="entry"><div class="entry-icon">↗</div><div class="entry-body"><strong>${[x.weight&&x.weight+' lb',x.length&&x.length+' in',x.head&&x.head+' in head'].filter(Boolean).join(' · ')}</strong><small>${esc(x.note||'Growth record')}</small></div><span class="entry-time">${fmtDate(x.date)}</span></div>`).join(''):"<div class=\"empty\">Our baby's measurements will appear here.</div>"}
const metric=(v,l)=>`<div class="metric"><strong>${v}</strong><small>${l}</small></div>`;
function renderMilestones(){let total=0,done=0;milestoneGroups.forEach(([,ms])=>ms.forEach(m=>{total++;if(data.milestones[m])done++}));$('#milestoneProgress').innerHTML=`<strong>${done} milestones celebrated</strong><p class="muted">CDC milestone checklists describe things most children (75% or more) can do by an age. If we have concerns about our baby's development, we should discuss them with our baby's clinician.</p><div class="progress"><i style="width:${done/total*100}%"></i></div>`;$('#milestoneList').innerHTML=milestoneGroups.map(([g,ms])=>`<div class="milestone-group"><h2>${g}</h2>${ms.map(m=>`<label class="milestone"><input type="checkbox" data-milestone="${encodeURIComponent(m)}" ${data.milestones[m]?'checked':''}><span>${m}</span></label>`).join('')}</div>`).join('');$$('[data-milestone]').forEach(c=>c.onchange=()=>{data.milestones[decodeURIComponent(c.dataset.milestone)]=c.checked?new Date().toISOString():false;save()})}
function renderInsights(){const cutoff=Date.now()-insightDays*86400000,logs=data.entries.filter(e=>new Date(e.time).getTime()>=cutoff),feeds=logs.filter(e=>e.type==='feed').length,diapers=logs.filter(e=>e.type==='diaper').length,sleep=logs.filter(e=>e.type==='sleep').reduce((a,e)=>a+(+e.duration||0),0);$('#insightCards').innerHTML=metric((feeds/insightDays).toFixed(1),'feeds/day')+metric((diapers/insightDays).toFixed(1),'diapers/day')+metric((sleep/60/insightDays).toFixed(1),'sleep hrs/day');const days=[];for(let i=insightDays-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const c=logs.filter(e=>new Date(e.time).toDateString()===d.toDateString()).length;days.push({d,c})}const max=Math.max(1,...days.map(x=>x.c));$('#activityChart').innerHTML=days.map((x,i)=>`<div class="bar-wrap"><div class="bar" style="height:${x.c/max*100}%" title="${x.c} logs"></div>${(insightDays<=7||i%5===0)?`<small>${x.d.toLocaleDateString([],{weekday:insightDays<=7?'short':undefined,day:insightDays>7?'numeric':undefined})}</small>`:''}</div>`).join('');$('#careSummary').innerHTML=[['Total logs',logs.length],['Feedings',feeds],['Diapers',diapers],['Recorded sleep',prettyMin(sleep)],['Tummy time',prettyMin(logs.filter(e=>e.type==='tummy').reduce((a,e)=>a+(+e.duration||0),0))]].map(x=>`<div class="summary-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function openEntry(type){$('#entryType').value=type;$('#entryTitle').textContent=`Log ${names[type]}`;$('#entryTime').value=localNow();$('#entryNote').value='';let h='';if(type==='feed')h='<label>Type<select id="detail"><option>Breast</option><option>Bottle</option><option>Formula</option><option>Solids</option></select></label><div class="two-col"><label>Amount<input id="amount" type="number" step="0.1" min="0" placeholder="Optional"></label><label>Unit<select id="unit"><option>oz</option><option>mL</option></select></label></div>';if(type==='diaper')h='<label>Type<select id="detail"><option>Wet</option><option>Dirty</option><option>Wet + dirty</option><option>Dry</option></select></label>';if(['sleep','tummy','pump'].includes(type))h='<label>Duration (minutes)<input id="duration" type="number" min="0" placeholder="Leave blank to start a timer"></label>';if(type==='medicine')h='<label>Medicine / dose as directed<input id="detail" placeholder="Log only — e.g. name and administered dose"></label>';$('#entryFields').innerHTML=h;$('#entryDialog').showModal()}
$('#entryForm').onsubmit=e=>{e.preventDefault();const type=$('#entryType').value,dur=$('#duration')?.value||'';data.entries.push({id:id(),type,time:$('#entryTime').value,detail:$('#detail')?.value||'',amount:$('#amount')?.value||'',unit:$('#unit')?.value||'',duration:dur,note:$('#entryNote').value,active:['sleep','tummy','pump'].includes(type)&&!dur});save();$('#entryDialog').close();toast(dur||!['sleep','tummy','pump'].includes(type)?'Entry saved':'Timer started')};
$('#growthForm').onsubmit=e=>{e.preventDefault();data.growth.push({id:id(),date:$('#growthDate').value,weight:$('#weight').value,length:$('#length').value,head:$('#head').value,note:$('#growthNote').value});save();$('#growthDialog').close();e.target.reset();toast('Measurement saved')};
$('#profileForm').onsubmit=e=>{e.preventDefault();data.profile={name:$('#babyName').value.trim(),birthDate:$('#birthDate').value,dueDate:$('#dueDate').value};save();$('#profileDialog').close();toast("Our baby's profile is saved")};
$$('[data-nav]').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.nav));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===b.dataset.nav));scrollTo(0,0);render()});$$('#quickActions button').forEach(b=>b.onclick=()=>openEntry(b.dataset.type));$('#addNote').onclick=()=>openEntry('note');$('#addGrowth').onclick=()=>{$('#growthDate').value=new Date().toISOString().slice(0,10);$('#growthDialog').showModal()};$('#profileBtn').onclick=()=>{$('#babyName').value=data.profile.name;$('#birthDate').value=data.profile.birthDate;$('#dueDate').value=data.profile.dueDate;$('#profileDialog').showModal()};$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#filters').onclick=e=>{if(e.target.dataset.filter){$$('#filters .chip').forEach(x=>x.classList.toggle('active',x===e.target));renderTimeline()}};$$('[data-days]').forEach(b=>b.onclick=()=>{insightDays=+b.dataset.days;$$('[data-days]').forEach(x=>x.classList.toggle('active',x===b));renderInsights()});
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`our-baby-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#importData').onchange=async e=>{try{const file=e.target.files?.[0];if(!file)return;const incoming=JSON.parse(await file.text());if(!incoming.profile||!Array.isArray(incoming.entries))throw Error();data={...fresh(),...incoming,profile:{...defaults.profile,...incoming.profile},entries:incoming.entries,growth:Array.isArray(incoming.growth)?incoming.growth:[],milestones:incoming.milestones||{}};save();$('#profileDialog').close();toast('Our backup was imported')}catch{toast('That backup could not be imported')}finally{e.target.value=''}};$('#clearData').onclick=()=>{if(confirm('Erase all Our Baby data stored in this browser?')){data=fresh();localStorage.removeItem(KEY);localStorage.removeItem(OLD);save();$('#profileDialog').close();toast('Local data erased')}};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
render();setInterval(renderTimers,30000);