import SwiftUI
import SwiftData
import Charts

struct GrowthView: View {
 @Query(sort:\GrowthRecord.date,order:.reverse) private var records:[GrowthRecord]; @Environment(\.modelContext) private var context; @State private var add=false
 var body:some View{ScrollView{VStack(alignment:.leading,spacing:16){if records.isEmpty{ContentUnavailableView("No measurements",systemImage:"chart.line.uptrend.xyaxis",description:Text("Add a measurement to start a growth history."))}else{if records.count>1{Chart(records.reversed()){r in if let w=r.weightPounds{LineMark(x:.value("Date",r.date),y:.value("Weight",w));PointMark(x:.value("Date",r.date),y:.value("Weight",w))}}.frame(height:220).card()};ForEach(records){r in HStack{VStack(alignment:.leading){Text(r.date,style:.date).bold();Text([r.weightPounds.map{"\($0) lb"},r.lengthInches.map{"\($0) in"},r.headInches.map{"\($0) in head"}].compactMap{$0}.joined(separator:" · ")).font(.caption).foregroundStyle(.secondary)};Spacer()}.card()}}}.padding()}.background(Color(.systemGroupedBackground)).navigationTitle("Growth").toolbar{Button{add=true}label:{Image(systemName:"plus")}}.sheet(isPresented:$add){GrowthForm()}}
}
struct GrowthForm:View{@Environment(\.dismiss)var dismiss;@Environment(\.modelContext)var context;@State var date=Date(),weight="",length="",head="",note="";var body:some View{NavigationStack{Form{DatePicker("Date",selection:$date,displayedComponents:.date);TextField("Weight (lb)",text:$weight).keyboardType(.decimalPad);TextField("Length (in)",text:$length).keyboardType(.decimalPad);TextField("Head circumference (in)",text:$head).keyboardType(.decimalPad);TextField("Note",text:$note)}.navigationTitle("Measurement").toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){context.insert(GrowthRecord(date:date,weightPounds:Double(weight),lengthInches:Double(length),headInches:Double(head),note:note));dismiss()}}}}}}

struct MilestonesView:View{@Query private var saved:[MilestoneRecord];@Environment(\.modelContext)var context;let groups:[(String,[String])]=[("2 months",["Calms down when spoken to or picked up","Looks at your face","Smiles when you talk to or smile at them","Reacts to loud sounds","Holds head up when on tummy"]),("4 months",["Smiles on own to get attention","Chuckles when you try to make them laugh","Makes sounds back when you talk","Turns head toward your voice","Brings hands to mouth"]),("6 months",["Knows familiar people","Laughs","Takes turns making sounds","Reaches to grab a toy","Rolls from tummy to back"]),("9 months",["Looks when name is called","Shows several facial expressions","Makes repeated sounds like mamamama","Sits without support"]),("1 year",["Plays games like pat-a-cake","Waves bye-bye","Looks for things they see you hide","Pulls up to stand"]),("18 months",["Points to show something interesting","Tries to say three or more words besides mama or dada","Walks without holding on","Scribbles"]),("2 years",["Notices when others are hurt or upset","Says at least two words together","Runs","Kicks a ball"]),("3 years",["Talks with at least two back-and-forth exchanges","Asks who, what, where, or why questions","Draws a circle when shown how","Uses a fork"])];var body:some View{List{Section{Text("A development journal, not a diagnostic or screening tool. CDC milestones describe things most children (75% or more) can do by an age.").font(.footnote).foregroundStyle(.secondary)};ForEach(groups,id:\.0){g in Section(g.0){ForEach(g.1,id:\.self){m in Button{toggle(m)}label:{HStack{Image(systemName:isDone(m) ? "checkmark.circle.fill":"circle").foregroundStyle(isDone(m) ? .green:.secondary);Text(m).foregroundStyle(.primary)}}}}}}.navigationTitle("Milestones")};func isDone(_ k:String)->Bool{saved.first{$0.key==k}?.completedAt != nil};func toggle(_ k:String){if let x=saved.first(where:{$0.key==k}){x.completedAt=x.completedAt==nil ? .now:nil}else{context.insert(MilestoneRecord(key:k,completedAt:.now))}}}

struct TimelineView:View{@Query(sort:\CareEntry.startedAt,order:.reverse)var entries:[CareEntry];@State var filter:CareType?;var body:some View{List{ScrollView(.horizontal,showsIndicators:false){HStack{Button("All"){filter=nil};ForEach([CareType.feed,.sleep,.diaper,.pump],id:\.self){t in Button(t.title){filter=t}}}};ForEach(entries.filter{filter==nil||$0.type==filter}){EntryRow(entry:$0)}}.navigationTitle("Timeline")}}

struct InsightsView:View{@Query var entries:[CareEntry];@State var days=7;var recent:[CareEntry]{entries.filter{$0.startedAt>Date().addingTimeInterval(Double(-days*86400))}};var body:some View{ScrollView{VStack(alignment:.leading,spacing:16){Picker("Range",selection:$days){Text("7 days").tag(7);Text("30 days").tag(30)}.pickerStyle(.segmented);HStack{Stat(value:avg(.feed),label:"feeds/day");Stat(value:avg(.diaper),label:"diapers/day");Stat(value:sleepAvg,label:"sleep hrs/day")}.card();Chart(daily,id:\.0){x in BarMark(x:.value("Day",x.0,unit:.day),y:.value("Logs",x.1))}.frame(height:220).card();Text("Insights summarize what you record; they do not determine whether feeding, sleep, growth, or development is medically appropriate.").font(.footnote).foregroundStyle(.secondary)}.padding()}.background(Color(.systemGroupedBackground)).navigationTitle("Insights")};func avg(_ t:CareType)->String{String(format:"%.1f",Double(recent.filter{$0.type==t}.count)/Double(days))};var sleepAvg:String{String(format:"%.1f",Double(recent.filter{$0.type == .sleep}.compactMap(\.durationMinutes).reduce(0,+))/60/Double(days))};var daily:[(Date,Int)]{(0..<days).reversed().map{i in let d=Calendar.current.startOfDay(for:Date().addingTimeInterval(Double(-i*86400)));return(d,recent.filter{Calendar.current.isDate($0.startedAt,inSameDayAs:d)}.count)}}}
